version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: smb-share
        target: /usr/share/nginx/html
        volume:
          nocopy: true
volumes:
  smb-share:
    driver_opts:
      type: cifs
      o: vers=2.0,guest
      device: "//<SMB_SERVER_IP>/<SHARE_NAME>"