services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: smb-share
        target: /usr/share/nginx/html
        volume:
          nocopy: true
      - ./default.conf:/etc/nginx/conf.d/default.conf  # Mount custom config
volumes:
  smb-share:
    driver_opts:
      type: cifs
      o: vers=2.0,guest,addr=192.168.1.178
      device: "//192.168.1.178/share"